### ISSUE TITLE
RecordTypes -> Picklistvalues not replaced properly

### ISSUE THREAD

**Issue by janbinderibm** [Stepan007/devops-toolkit#9]
<recordTypes>
        <fullName>Commercial_Account</fullName>
        <active>true</active>
        <description>Standard Commercial Account</description>
        <label>Commercial Account</label>
        <picklistValues>
            <picklist>AccountSource</picklist>
            <values>
                <fullName>Other</fullName>
                <default>false</default>
            </values>
        </picklistValues>
        <picklistValues>
            <picklist>ChannelDeliveredtoGfK__c</picklist>
            <values>
                <fullName>AVSpec</fullName>
                <default>false</default>
            </values>
            <values>
                <fullName>AgrEqSp</fullName>
                <default>false</default>
            </values>

**Comment by Stepan007** [comment]
I believe I fixed this in update_xml_new.py
